# Generated by Django 4.1 on 2022-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='month_name',
            field=models.CharField(max_length=100),
        ),
    ]
