# Generated by Django 4.1 on 2023-01-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='radius',
            field=models.FloatField(),
        ),
    ]
