# Generated by Django 4.1 on 2022-09-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Given', max_length=100)),
                ('email', models.CharField(default='Not Given', max_length=100)),
                ('department', models.CharField(default='Not Given', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', max_length=20)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='main.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Given', max_length=60)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('late_join', models.BooleanField(blank=True, default=False, null=True)),
                ('location_in', models.CharField(blank=True, max_length=500, null=True)),
                ('location_in_url', models.CharField(blank=True, max_length=500, null=True)),
                ('delay_in', models.CharField(default='-', max_length=50, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('late_leave', models.BooleanField(blank=True, default=False, null=True)),
                ('location_out', models.CharField(blank=True, max_length=500, null=True)),
                ('location_out_url', models.CharField(blank=True, max_length=500, null=True)),
                ('delay_out', models.CharField(default='-', max_length=50, null=True)),
                ('total_hours', models.CharField(default='-', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='main.registereduser')),
            ],
        ),
    ]
