# Generated by Django 4.0.4 on 2022-08-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registered_user',
            new_name='RegisteredUser',
        ),
        migrations.RenameModel(
            old_name='User_image',
            new_name='UserImage',
        ),
    ]
