# Generated by Django 4.1 on 2022-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_out',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
