# Generated by Django 4.1 on 2023-01-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_log_total_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
