# Generated by Django 4.1 on 2022-08-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_log_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
