# Generated by Django 4.1 on 2022-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_log_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='total_hours',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
