# Generated by Django 4.1 on 2022-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Given', max_length=60)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.CharField(default=' - ', max_length=60)),
            ],
        ),
    ]
