# Generated by Django 4.1 on 2022-08-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_log_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateField(blank=True, null=True)),
                ('time_out', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
