# Generated by Django 4.1 on 2022-08-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_log_late_join_log_late_leave_timing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='location_in',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='location_out',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
