# Generated by Django 4.1 on 2022-08-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_log_delay_in_log_delay_out_alter_log_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
